lanes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from ajax_select import urls as ajax_select_urls
import django_pydenticon.urls

from .views import *
admin.autodiscover()


urlpatterns = [
    url(r'^ajax/users/c/$', UserJsonView.as_view(data='org'), name='ajax_users_org'),
    url(r'^ajax/c/all/$', OrgJsonView.as_view(data='all'), name='ajax_orgs_all'),
    url(r'^ajax/c/mine/$', OrgJsonView.as_view(data='mine'), name='ajax_orgs_mine'),
    url(r'^ajax/c/followed/$', OrgJsonView.as_view(data='followed'), name='ajax_orgs_watching'),
    url(r'^ajax/c/search/$', OrgJsonView.as_view(data='search'), name='ajax_orgs_search'),
    url(r'^ajax/select/', include(ajax_select_urls)),
    url(r'^create/$', OrgCreateView.as_view(), name='create_org'),

    url(r'^c/(?P<slug>[\w-]+)/$', OrgView.as_view(), name='org'),
    url(r'^c/(?P<slug>[\w-]+)/manage/$', OrgManagementView.as_view(), name='manage_org'),
    url(r'^c/(?P<slug>[\w-]+)/manage/approval/$', OrgApprovalView.as_view()),
    url(r'^c/(?P<slug>[\w-]+)/add_room/$', RoomAddView.as_view(), name='add_room'),
    url(r'^c/(?P<slug>[\w-]+)/join/$', OrgJoinView.as_view()),
    url(r'^c/(?P<slug>[\w-]+)/apply/$', OrgApplyView.as_view()),
    url(r'^c/(?P<slug>[\w-]+)/follow/$', OrgWatchView.as_view()),
    url(r'^c/(?P<slug>[\w-]+)/status/$', OrgStatusView.as_view(), name='org_status'),
    url(r'^c/(?P<slug>[\w-]+)/invite/$', OrgInviteView.as_view(), name='org_invite'),
    url(r'^c/(?P<slug>[\w-]+)/banned/$', BannedView.as_view(), name='banned'),
    url(r'^c/(?P<slug>[\w-]+)/dm/(?P<username>[\w-]+)/$', DMView.as_view(), name='dm'),

    url(r'^c/(?P<slug>[\w-]+)/bot/create/$', BotCreateView.as_view(), name='bot_create'),
    url(r'^c/(?P<slug>[\w-]+)/bot/(?P<username>[\w-]+)/$', BotUpdateView.as_view(), name='bot'),
    url(r'^c/(?P<slug>[\w-]+)/bot/(?P<username>[\w-]+)/create_token/$', BotTokenCreateView.as_view(), name='bot_token_create'),
    url(r'^c/(?P<slug>[\w-]+)/bot/(?P<username>[\w-]+)/delete/$', BotDeleteView.as_view(), name='bot_delete'),

    url(r'^room/(?P<room_id>\d+)/$', RoomView.as_view(), name='room'),
    url(r'^room/(?P<room_id>\d+)/post/$', RoomMessageView.as_view(), name='room_post'),
    url(r'^room/(?P<room_id>\d+)/pin/$', RoomPinView.as_view(), name='room_pin'),
    url(r'^room/(?P<room_id>\d+)/edit/$', RoomEditView.as_view(), name='room_edit'),
    url(r'^room/(?P<room_id>\d+)/prefs/$', RoomPrefsView.as_view(), name='room_prefs'),
    url(r'^room/(?P<room_id>\d+)/add_member/$', RoomMemberView.as_view(), name='room_member'),
    url(r'^room/(?P<room_id>\d+)/bot/(?P<username>[\w-]+)/enable/$', BotEnableView.as_view(), name='bot_enable'),

    url(r'^post/(?P<post_id>\d+)/edit/$', PostEditView.as_view(), name='post_edit'),
    url(r'^post/(?P<post_id>\d+)/flag/$', PostFlagView.as_view(), name='post_flag'),
    url(r'^post/(?P<post_id>\d+)/vote/$', PostVoteView.as_view(), name='post_vote'),
    url(r'^post/(?P<post_id>\d+)/history/$', PostHistoryView.as_view(), name='post_history'),

    url(r'^users/(?P<user_id>\d+)/$', UserProfileView.as_view(), name='user_profile'),
    url(r'^users/(?P<user_id>\d+)/picture/$', UserPictureView.as_view(), name='user_picture'),
    url(r'^users/(?P<user_id>\d+)/ban/$', UserBanView.as_view(), name='user_ban'),
    url(r'^users/(?P<user_id>\d+)/unban/$', UserUnbanView.as_view(), name='user_unban'),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^users/register/(?P<token>\w+)/', RegisterView.as_view(), name='invitation'),
    url(r'^users/register/$', RegisterView.as_view(), name='register'),
    url(r'^users/recover/$', PasswordRecoveryView.as_view(), name='forgotten_password'),
    url(r'^users/reset/(?P<token>\w+)/$', PasswordResetView.as_view(), name='reset_password'),

    url(r'^$', LandingView.as_view(), name='orgs'),
    url(r'^request_invitation/$', InvitationRequestView.as_view(), name='invitation_request'),

    url(r'^identicon/', include(django_pydenticon.urls.get_patterns())),

    url(r'^admin/', include(admin.site.urls), name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = Error500.as_view()
handler403 = Error404.as_view()
handler404 = Error404.as_view()
handler500 = Error500.as_view()

lanes/models.py
import base64
import hashlib
import json
import logging
import math
import os
import random
import string
import uuid

from datetime import datetime, timedelta

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.utils import timezone

from easy_thumbnails.files import get_thumbnailer

from ws4redis.redis_store import RedisMessage
from ws4redis.publisher import RedisPublisher

from autoslug import AutoSlugField

hasher = hashlib.new('ripemd160')

logger = logging.getLogger('django')

epoch = timezone.make_aware(datetime(1970, 1, 1), timezone.get_current_timezone())


class Organisation(models.Model):
  """ An organisation or community """

  PRIVACY_OPEN = 0       # Anyone can join, no approval
  PRIVACY_APPLY = 1      # Anyone can apply to join
  PRIVACY_INVITE = 2     # Must have an invitation to join
  PRIVACY_ORG = 3        # Must be a member of an org

  PRIVACY_CHOICES = (
      (PRIVACY_OPEN, "Open"),
      (PRIVACY_APPLY, "Application Only"),
      (PRIVACY_INVITE, "Invitation Only"),
      (PRIVACY_ORG, "Your domain")
  )

  VISIBILITY_PUBLIC = 0   # Visible in search
  VISIBILITY_LINK = 1     # Not visible in search, accessible by link
  VISIBILITY_PRIVATE = 2  # Only accessible by invite

  VISIBILITY_CHOICES = (
      (VISIBILITY_PUBLIC, "Public"),
      (VISIBILITY_LINK, "Link Only"),
      (VISIBILITY_PRIVATE, "Private"),
  )

  name = models.CharField(max_length=200)
  domain = models.CharField(max_length=200, unique=True, null=True, blank=True)
  admins = models.ManyToManyField(settings.AUTH_USER_MODEL)
  privacy = models.IntegerField(choices=PRIVACY_CHOICES, default=PRIVACY_APPLY)
  visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=VISIBILITY_LINK)
  slug = AutoSlugField(populate_from='name', unique=True)

  def get_users(self):
    return User.objects.filter(organisations__id__exact=self.id)

  users = property(get_users)

  def __str__(self):
    return self.name


def generate_token():
  return ''.join(random.SystemRandom().choice(
      string.ascii_uppercase + string.digits + string.ascii_lowercase
  ) for _ in range(20))


def uuid_filename(instance, filename):
    name = base64.b64encode(uuid.uuid4().bytes).decode('utf-8').replace('==','').replace('/','-')
    _, ext = os.path.splitext(filename)
    name += ext
    return 'user_{0}/{1}'.format(instance.id, name)


class Invitation(models.Model):
  """ An invitation to join a specific org """
  organisation = models.ForeignKey(Organisation)
  email = models.EmailField()
  token = models.CharField(max_length=20, default=generate_token, unique=True)

  def __str__(self):
    return self.organisation.name + " - " + self.email


class Bot(models.Model):
  """ A profile for a bot, which belongs to a bot user """
  SCOPE_GLOBAL = 0
  SCOPE_LOCAL = 1

  SCOPES = ((SCOPE_GLOBAL, "All rooms"),
            (SCOPE_LOCAL, "Only certain rooms"),)

  notify_url = models.URLField()  # URL to hit with @pings
  notify_key = models.CharField(max_length=20, default=generate_token)  # Key to include in notifications
  organisation = models.ForeignKey(Organisation, related_name="org")
  rooms = models.ManyToManyField('Room', blank=True)
  scope = models.IntegerField(choices=SCOPES, default=SCOPE_LOCAL)
  owner = models.ForeignKey('User', related_name="owner")

  def responds_to(self, room):
    return room in self.rooms.all() or (room.organisation == self.organisation and
                                        self.scope == self.SCOPE_GLOBAL)

  def get_tokens(self):
    return BotToken.objects.filter(bot=self)

  def __str__(self):
    try:
      return self.organisation.name + ": " + self.user.username
    except:
      return self.organisation.name + " (no user yet)"


class BotToken(models.Model):
  """ A token used by bots to authenticate """
  bot = models.ForeignKey(Bot)
  token = models.CharField(max_length=20, default=generate_token, unique=True)
  created = models.DateTimeField(auto_now_add=True)


class User(AbstractUser):
  """ A user """

  is_bot = models.BooleanField(default=False)
  bot = models.OneToOneField(Bot, null=True)
  organisations = models.ManyToManyField(Organisation, through='OrgMembership')
  subscribed = models.ManyToManyField(Organisation, related_name='subscribed', blank=True)
  profile_image = models.ImageField(upload_to=uuid_filename, null=True, blank=True)
  hash = models.CharField(max_length=40)

  def save(self, *args, **kwargs):
    if not self.hash:
      h = hashlib.new('ripemd160')
      h.update(self.username.encode('utf-8') + b'saltymcsaltface')
      self.hash = h.hexdigest()
    super(User, self).save(*args, **kwargs)

  def get_image(self):
    if self.profile_image:
      options = {'size': (300, 300), 'crop': True}
      return get_thumbnailer(self.profile_image).get_thumbnail(options).url
    else:
      return reverse("django_pydenticon:image", kwargs={"data": self.hash + '.png'})

  def is_admin(self, org):
    return self in org.admins.all()

  def is_member(self, org):
    return org in self.organisations.all()

  def is_subscribed(self, org):
    return org in self.subscribed.all()

  def get_rooms(self):
    return Room.objects.filter(members__in=[self])

  def get_orgs(self):
    memberships = OrgMembership.objects.filter(user=self).values_list('organisation__pk', flat=True)
    return Organisation.objects.filter(id__in=memberships)

  def get_status(self, org):
    return OrgMembership.objects.get(user=self, organisation=org).status

  def notify(self, post):
    if self.is_bot and self.bot.responds_to(post.room):
      from .tasks import ping_bot
      ping_bot.delay(post, self)
    elif self.get_status(post.room.organisation) in [OrgMembership.STATUS_AWAY, OrgMembership.STATUS_OFFLINE]:
      Notification(post=post, user=self).save()

  def set_status(self, org, status):
    m = OrgMembership.objects.get(user=self, organisation=org)
    m.status = status
    m.save()
    message = {
        "type": "status",
        "id": self.id,
        "status": m.status,
        "username": self.username,
        "img": self.get_image()
    }
    RedisPublisher(facility='org_' + org.slug, broadcast=True) \
        .publish_message(RedisMessage(json.dumps(message)))

  def can_view(self, room):
    if room.organisation not in self.organisations.all() and \
        room.organisation.visibility == Organisation.VISIBILITY_PRIVATE:
      logger.debug("not a member of private org")
      return False
    if room.privacy == Room.PRIVACY_PUBLIC:
      return True
    if self.is_admin(room.organisation):
      return True
    if self in room.members.all():
      return True
    logger.debug("Not a member or admin of private room")
    return False

  def ban_for(self, org, seconds):
    membership = OrgMembership.objects.get(user=self, organisation=org)
    membership.ban_expiry = timezone.now() + timedelta(0, seconds)
    membership.save()
    BanLog(user=self, organisation=org, duration=seconds).save()

  def unban(self, org):
    membership = OrgMembership.objects.get(user=self, organisation=org)
    membership.ban_expiry = None
    membership.save()
    BanLog(user=self, organisation=org, duration=0).save()

  def is_banned(self, org):
    membership = OrgMembership.objects.get(user=self, organisation=org)
    if membership.ban_expiry is not None:
      if timezone.now() < membership.ban_expiry:
        return True
      else:
        membership.ban_expiry = None
        membership.save()
        return False
    else:
      return False

  def __str__(self):
    return self.username


class OrgMembership(models.Model):
  """ through class for user membership of orgs """
  ADMIN = 0
  USER = 1
  ROLES = (
      (ADMIN, 'Admin'),
      (USER, 'User')
  )

  STATUS_ONLINE = 0
  STATUS_AWAY = 1
  STATUS_BUSY = 2
  STATUS_INVISIBLE = 3
  STATUS_OFFLINE = 4

  STATUS_CHOICES = (
      (STATUS_ONLINE, "online"),
      (STATUS_AWAY, "away"),
      (STATUS_BUSY, "busy"),
      (STATUS_INVISIBLE, "invisible"),
      (STATUS_OFFLINE, "offline")
  )

  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
  status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_ONLINE)
  role = models.IntegerField(choices=ROLES, default=USER)
  ban_expiry = models.DateTimeField(null=True, blank=True)

  class Meta:
    unique_together = ('user', 'organisation',)

  def __str__(self):
    return str(self.organisation) + " - " + str(self.user)


class OrgApplication(models.Model):
  """ An application by a user to an organisation """

  organisation = models.ForeignKey(Organisation)
  user = models.ForeignKey(User)
  created = models.DateTimeField(auto_now_add=True)
  rejected = models.BooleanField(default=False)

  class Meta:
    unique_together = ('user', 'organisation',)


class Room(models.Model):
  """ A chat room """

  PRIVACY_PUBLIC = 0   # Anyone can see, chat
  PRIVACY_PRIVATE = 1  # Only members and mods can see

  PRIVACY_CHOICES = (
      (PRIVACY_PUBLIC, "Public"),
      (PRIVACY_PRIVATE, "Private")
  )

  name = models.CharField(max_length=100)
  topic = models.CharField(max_length=200)
  organisation = models.ForeignKey(Organisation)
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='creator')
  created = models.DateTimeField(auto_now_add=True)
  owners = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='owners')
  members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='members')
  privacy = models.IntegerField(choices=PRIVACY_CHOICES, default=PRIVACY_PRIVATE)
  is_dm = models.BooleanField(default=False)

  def get_history(self):
    posts = Post.objects.filter(room=self).order_by('-created')[:100]
    return posts[::-1]

  history = property(get_history)

  def get_pinned(self):

lanes/forms.py
import logging
import re

from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import RadioSelect, HiddenInput
from ajax_select import make_ajax_field

from .models import Organisation, OrgMembership, Room, User, Bot

logger = logging.getLogger('django')
username_test = re.compile("^([a-z0-9]+)+$")


def validate_username(value):
  if User.objects.filter(username=value).count() > 0:
    raise forms.ValidationError('That username is already in use')
  if not username_test.match(value):
    raise forms.ValidationError('')
  return value


class OrgForm(ModelForm):

  class Meta:
    model = Organisation
    fields = ['name', 'privacy', 'visibility', 'admins', 'domain']
    widgets = {
        'privacy': RadioSelect(attrs={'class': 'radio-4'}),
        'visibility': RadioSelect(),
        'domain': HiddenInput()
    }

  admins = make_ajax_field(Organisation, 'admins', 'users', required=True, help_text="")


class OrgEditForm(ModelForm):
  class Meta:
    model = Organisation
    fields = ['admins']

  admins = make_ajax_field(Organisation, 'admins', 'users', required=True, help_text="")


class RoomForm(ModelForm):

  class Meta:
    model = Room
    fields = ['name', 'topic', 'privacy', 'owners']
    widgets = {
        'privacy': RadioSelect(attrs={'class': 'radio-2'}),
    }

  owners = make_ajax_field(Room, 'owners', 'users', required=True, help_text="")


class BotCreateForm(ModelForm):

  username = forms.CharField(label='Name')

  class Meta:
    model = Bot
    fields = ['username', 'notify_url', 'scope']
    widgets = {
        'scope': RadioSelect(attrs={'class': 'radio-2'}),
    }
    help_texts = {
        'username': 'Enter a valid username, numbers and letters only.',
    }
    error_messages = {
        'username': {
            'invalid': "",
            'max_length': "This name is too long.",
        },
    }

  def clean_username(self):
    return validate_username(self.cleaned_data.get("username").lower())


class BotUpdateForm(ModelForm):

  class Meta:
    model = Bot
    fields = ['scope']
    widgets = {
        'scope': RadioSelect(attrs={'class': 'radio-2'}),
    }


class RegisterForm(UserCreationForm):
  secret_key = forms.CharField(label='Secret Key', widget=forms.PasswordInput())

  class Meta(UserCreationForm.Meta):
    model = User
    fields = UserCreationForm.Meta.fields + ('secret_key', 'email')
    help_texts = {
        'username': 'Enter a valid username, numbers and letters only.',
    }
    error_messages = {
        'username': {
            'invalid': "",
            'max_length': "This username is too long.",
        },
    }

  def clean_username(self):
    return validate_username(self.cleaned_data.get("username").lower())

  def clean_email(self):
    value = self.cleaned_data.get("email").lower()
    if User.objects.filter(email=value).count() > 0:
      raise forms.ValidationError('That address is already in use')
    return value

  def clean_secret_key(self):
    if self.cleaned_data.get("secret_key") != "goldfish":
      raise forms.ValidationError("Incorrect Secret Key")
    return ""

  def save(self, *args, **kwargs):
    logger.debug("Saving")
    user = super(RegisterForm, self).save(*args, **kwargs)
    domain = user.email.split('@')[1]
    orgs = Organisation.objects.filter(domain=domain)
    if orgs.count() == 1:
      OrgMembership(user=user, organisation=orgs[0]).save()
    return user

lanes/templates/add_room.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Add a Room{% endblock %}

{% block main_content %}
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <form action="." method="post" role="form">
      <input type="hidden" name="org_id" value="{{ org.id }}">
      <legend>Add a new Room</legend>
      {% csrf_token %}
      {{ form|bootstrap }}
      <div class="form-group">
        <button type="submit" class="btn btn-success btn-lg">Add Room</button>
      </div>
    </form>
  </div>
</div>
{% endblock main_content %}

{% block script_panel %}
<script type="text/javascript" src="/static/ajax_select/js/ajax_select.js"></script>
{% endblock %}

lanes/templates/banned.html
{% extends "base.html" %}

{% block title %}Banned{% endblock %}

{% block main_content %}
<h1>You have been banned from {{ org.name }}</h1>
<p class="alert alert-danger">Your ban will expire in {{ remaining }}.</p>
{% endblock main_content %}

lanes/templates/error_404.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Oh dear :({% endblock %}

{% block main_content %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <legend>Oh dear :(</legend>
    <p class="alert alert-danger">It doesn't look like that page exists.</p>
  </div>
</div>
{% endblock main_content %}

lanes/templates/error_500.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Oh dear :({% endblock %}

{% block main_content %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <legend>Oh dear :(</legend>
    <p class="alert alert-danger">Something has gone wrong, but don't worry, we're looking into it already.</p>
  </div>
</div>
{% endblock main_content %}

lanes/templates/manage_org.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}{{ org.name }}{% endblock %}

{% block org_admin_active %}active{% endblock %}

{% block main_content %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <form action="{% url 'manage_org' org.slug %}" method="post">
      {% csrf_token %}
      <legend>Manage {{ org.name }}</legend>
      {{ form|bootstrap }}
      <button class="btn btn-success" type="submit">Apply Changes</button>
    </form>

    {% if org.privacy == org.PRIVACY_APPLY %}
    <hr>

    <div style="display:none;" id="user-list">
      <legend>Users awaiting approval</legend>
      <div class="list-group">
      {% for a in applications %}
        <div class="list-group-item">
          {{ a.user.username }}
          <div class="btn-group pull-xs-right application">
            <button class="btn approval btn-xs btn-danger" data-action="deny" data-id="{{ a.user.id }}">Deny</button>
            <button class="btn approval btn-xs btn-success" data-action="approve" data-id="{{ a.user.id }}">Approve</button>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
    <div style="display:none;" id="no-users" class="alert alert-info">There are no users awaiting approval</div>
    {% endif %}

    <hr>

    <legend>Invite someone to join {{ org.name }}</legend>
    <div class="form-group">
      <input class="form-control" type="email" name="email" placeholder="Email" id="id_email">
    </div>
    <button type="button" class="btn btn-success" id="send-invite">Send Invite</button>
    <div class="form-group">
      <p id="message" class="helptext text-success" style="display:none;">An invitation has been sent</p>
    </div>

    <hr>

    <legend>Bots for {{ org.name }}</legend>
    <div class="list-group">
    {% for bot in bots %}
      <div class="list-group-item">
        <a href="{% url 'bot' org.slug bot.username %}">{{ bot.username }} - {{ bot.bot.get_scope_display }}</a>
        <div class="btn-group pull-xs-right application">
          <form action="{% url 'bot_delete' org.slug bot.username %}" method="post">
            {% csrf_token %}
            <button class="btn btn-xs btn-danger">Remove</button>
          </form>
        </div>
      </div>
    {% endfor %}
    </div>
    <a href="{% url 'bot_create' org.slug %}" class="btn btn-primary"><i class="fa fa-plus"></i> Add a new bot</a>
  </div>
</div>
{% endblock main_content %}

{% block script_panel %}
<script type="text/javascript" src="/static/ajax_select/js/ajax_select.js"></script>
<script type="text/javascript">
  $(document).ready(function(){

    {% if applications.count > 0 %}
      $("#user-list").show();
    {% else %}
      $("#no-users").show();
    {% endif %}

    $('.approval').on('click',function(){
      var self = $(this);
      self.parent().find('.btn').attr('disabled', 'disabled');
      $.ajax({
        url:"/c/{{ org.slug }}/manage/approval/",
        method:"post",
        data:{
          action:self.attr('data-action'),
          id:self.attr('data-id')
        },
        success: function(){
          self.parent().parent().slideUp('fast');
          if($(".application:visible").length == 0){
            $("#user-list").hide();
            $("#no-users").show();
          }
        }
      });
    });

    function send(){
      $('#send-invite').addClass('disabled');
      $('#send-invite').prop('disabled', true);
      $.ajax({
        method: "post",
        url: "{% url 'org_invite' org.slug %}",
        dataType: "json",
        data: {
          email: $('#id_email').val(),
          organisation: {{ org.id }}
        },
        success: function(){
          $('#id_email').val('');
          $('#message')
            .text('An invitation has been sent!')
            .addClass('text-success')
            .removeClass('text-danger')
            .fadeIn('fast');
        },
        error: function(response){
          var data = JSON.parse(response.responseText);
          var message = "Something went wrong :-("
          if (data.email){
            message = data.email;
          }
          $('#message')
            .text(message)
            .removeClass('text-success')
            .addClass('text-danger')
            .fadeIn('fast');
        },
        complete: function(){
          setTimeout(function(){
            $('#message').fadeOut('slow');
          },2000);
          $('#send-invite').removeClass('disabled');
          $('#send-invite').prop('disabled', false);
        }
      });
    }

    $("#id_email").keydown(function(ev) {
      if (ev.keyCode === 13 && !ev.shiftKey) {
        send();
      }
    });

    $('#send-invite').on('click',function(){
      send();
    });
  });
</script>
{% endblock %}

lanes/templates/orgs.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Communities{% endblock %}

{% block orgs_active %}active{% endblock %}

{% block main_content %}
<ul class="nav nav-tabs" id="org-selection">
  <li class="nav-item" role="presentation"><a class="nav-link" data-url="mine" href="#mine">Mine</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" data-url="followed" href="#followed">Followed</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" data-url="all" href="#all">All</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" href="#search"><i class="fa fa-search"></i> Search</a></li>
  <a href="{% url 'create_org' %}" class="btn btn-success btn-sm action-button"><i class="fa fa-plus"></i> Create new community</a>
</ul>
<div id="search" style="display:none;">
  <input class="form-control" id="search-input" placeholder="Search for Communities">
</div>
<div class="spinner"></div>
<div class="list-group" id="org-list"></div>
{% endblock main_content %}

{% block script_panel %}
<script type="text/javascript">
$(document).ready(function(){

  var hash = window.location.hash.substring(1);
  var spin = 0;
  if (hash !== "" && ["mine","all","followed"].indexOf(hash) >= 0) {
    setTab(hash);
  } else {
    setTab('mine');
  }

  function setTab(url){
    if(url == "search"){
      url = "mine";
    }
    var el = $('#org-selection a[data-url="' + url + '"]');
    el.tab('show');
    el.parent().addClass('active');
    updateContent(url);
  }

  $('#org-selection li a').click(function (e) {
    if($(this).parent().hasClass('active')){
      return;
    }
    $(this).tab('show');
    $('a').removeClass('active');
    $(this).addClass('active');
    if($(this).attr('data-url')) {
      endSearch();
      updateContent($(this).attr('data-url'))
    } else {
      startSearch();
    }
  });

  function handleData(data){
    $('#org-list').html('');
    if (data.orgs.length === 0) {
      $('#org-list').append('<div class="list-group-item">No communities found :(</div>');
    }
    data.orgs.forEach(function(o){
      $('#org-list').append(
        '<a href="/c/' + o.slug + '" class="list-group-item">' + o.name + '</a>'
      );
    });
    clearTimeout(spin);
    $('.spinner').hide();
  }

  function updateContent(filter){
    window.location.hash = '#' + filter;
    $('#org-list').html('');
    clearTimeout(spin);
    spin = setTimeout(function(){$('.spinner').show();},1000);
    $.ajax({
      method: "get",
      url: "/ajax/c/" + filter + "/",
      success: handleData
    })
  }

  function startSearch(){
    $("#search").show();
    $('#org-list').html('');
    $("#search-input").focus();
  }

  function endSearch(){
    $('#search').hide();
  }

  $("#search-input").on('keyup',function(){
    var text = $(this).val();
    if(text !== ""){
      $.ajax({
        method:"get",
        url:"/ajax/c/search/?s=" + encodeURIComponent(text),
        success: handleData
      });
    }
  });
});
</script>
{% endblock %}